#!/bin/bash

# Extract data using jq and format with awk
jq -r '.name, .height, .weight, .types[0].type.name' data.json | awk '
NR==1 {name=$0}
NR==2 {height=$0/10}
NR==3 {weight=$0/10}
NR==4 {type=$0}
END {
    name = toupper(substr(name,1,1)) substr(name,2)
    type = toupper(substr(type,1,1)) substr(type,2)
    printf "%s is of type %s, weighs %gkg, and is %gm tall.\n", name, type, weight, height
}'