#!/bin/bash

# Extract data using jq, sed, and awk
name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')
formatted_height=$(jq -r '.height' data.json | awk '{print $1/10}')
formatted_weight=$(jq -r '.weight' data.json | awk '{print $1/10}')

echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."